### ISSUE TITLE
Error: $map2: "default" is not a map for `map-merge'

### ISSUE THREAD

**Issue by alok108** [owldesign/Hydrogen-HTML5#1]
I am getting this error after running grunt
```
Error: $map2: "default" is not a map for `map-merge'
        on line 55 of dev/scss/lib/grid/_functions.scss, in `_gridle_container_common'
        from line 92 of dev/scss/lib/grid/_mixins.scss, in `gridle_container'
        from line 9 of dev/scss/layout/_layout.scss
        from line 33 of ./dev/scss/application.scss
```

**Comment by owldesign** [comment]
Looks like a griddle layouts issue. I updated grunt dependencies though they were WAY out of date. I'll have to redo the grid for this. Will work on it tonight.

**Comment by owldesign** [comment]
@alok108 You should pull new updated code. I removed girddle as it was also super outdated. I just added our own responsive styles. Good luck.
